name: Generar y subir YouTube Short

on:
  workflow_dispatch:

jobs:
  generar-y-subir:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Instalar FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Generar video
        run: python script.py

      - name: Guardar video
        uses: actions/upload-artifact@v4
        with:
          name: forge-short
          path: forge_short.mp4

      - name: Subir a YouTube
        env:
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: python upload_youtube.py
