name: Generar video

on:
  workflow_dispatch:

jobs:
  generar-video:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Instalar FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Generar video
        run: python script.py
